const allRouterObj=[
    // 用户模块
    {
        routerUrls:'/api/user/login',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/userlist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/addlist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/register',
        menuUrl:'/',
        permit:null
    },
    {
        routerUrl:'/api/user/dellist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/updatelist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/isactiveuser',
        menuUrl:'/sys/user',
        permit:null
    },
    // 角色模块
    {
        routerUrl:'/api/role/addrole',
        menuUrl:'/sys/role',
        permit:null
    },
    {
        routerUrl:'/api/role/updaterole',
        menuUrl:'/sys/role',
        permit:'editRole'
    },
    {
        routerUrl:'/api/role/deleterole',
        menuUrl:'/sys/role',
        permit:null
    },
    {
        routerUrl:'/api/role/rolelist',
        menuUrl:'/sys/role',
        permit:null
    },
    // 菜单模块
    {
        routerUrl:'/api/menus/addmenulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/delMenuList',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/updatemenulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/menulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/ask',
        menuUrl:'/chat',
        permit:null
    },
    {
        routerUrl:'/api/auth/emailcode',
        menuUrl:'/',
        permit:null
    },
    // chatgpt管理---参数配置模块
    {
      routerUrl:'/api/gptparam/chatparam',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/gptparam/modelparam',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/gptparam/userchatparam',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    // chatgpt管理---账号管理模块
    {
        routerUrl:'/api/gptaccount/accountlist',
        menuUrl:'/chatgpt/account',
        permit:null
    },
    {
        routerUrl:'/api/gptaccount/apikey',
        menuUrl:'/chatgpt/account',
        permit:null
    },
    // chatgpt管理---聊天参数配置模块
    {
        routerUrl:'/api/chatgpt/chatparams',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/officalkeylist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/officalkeysetting',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/unofficalkeysetting',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/unofficaltokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/bingtokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/bardtokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/claudetokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/huggingtokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/xfyuntokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/poetokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/chatglmtokenlist',
        menuUrl:'/chatgpt/setting',
        permit:null
    },
    // chatgpt管理---资源管理模块
    {
        routerUrl:'/api/chatgpt/keylist',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onekey',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/keylist/keystatus',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/tokenlist',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onetoken',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/tokenlist/enablestatus',
        menuUrl:'/chatgpt/resource/chatgpt',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/binglist',
        menuUrl:' /chatgpt/resource/newbing',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onebing',
        menuUrl:' /chatgpt/resource/newbing',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/binglist/bingstatus',
        menuUrl:' /chatgpt/resource/newbing',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/bardlist',
        menuUrl:' /chatgpt/resource/googlebard',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onebard',
        menuUrl:' /chatgpt/resource/googlebard',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/bardlist/bardstatus',
        menuUrl:' /chatgpt/resource/googlebard',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/claudelist',
        menuUrl:' /chatgpt/resource/claude',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/oneclaude',
        menuUrl:' /chatgpt/resource/claude',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/claudelist/claudestatus',
        menuUrl:' /chatgpt/resource/claude',
        permit:null
    },
    // hugging
    {
        routerUrl:'/api/chatgpt/hugginglist',
        menuUrl:'/chatgpt/resource/hugging',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onehugging',
        menuUrl:'/chatgpt/resource/hugging',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/hugginglist/huggingstatus',
        menuUrl:'/chatgpt/resource/hugging',
        permit:null
    },
    // xfyun
    {
        routerUrl:'/api/chatgpt/xfyunlist',
        menuUrl:'/chatgpt/resource/xfyun',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onexfyun',
        menuUrl:'/chatgpt/resource/xfyun',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/hugginglist/xfyunstatus',
        menuUrl:'/chatgpt/resource/xfyun',
        permit:null
    },
    // poe
    {
        routerUrl:'/api/chatgpt/poelist',
        menuUrl:'/chatgpt/resource/poe',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onepoe',
        menuUrl:'/chatgpt/resource/poe',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/poelist/poestatus',
        menuUrl:'/chatgpt/resource/poe',
        permit:null
    },
    // chatglm
    {
        routerUrl:'/api/chatgpt/chatglmlist',
        menuUrl:'/chatgpt/resource/chatglm',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/onechatglm',
        menuUrl:'/chatgpt/resource/chatglm',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/chatglmlist/chatglmstatus',
        menuUrl:'/chatgpt/resource/chatglm',
        permit:null
    },
    // chatgpt管理---对话指标模块
    {
        routerUrl:'/api/chatgpt/interfaceratelist',
        menuUrl:'/chatgpt/distribute',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/interfacepricelist',
        menuUrl:'/chatgpt/distribute',
        permit:null
    },
    // 首页统计模块
    {
        routerUrl:'/api/homestatistics/chatStatistics',
        menuUrl:'/',
        permit:null
    },
    {
        routerUrl:'/api/homestatistics/chatdetaildata',
        menuUrl:'/',
        permit:null
    },
    // 对话模块
    {
        routerUrl:'/api/chatgpt/xunfeigttoken',
        menuUrl:'/chatgpt/chat',
        permit:null
    }
]

module.exports=allRouterObj