const allRouterObj=[
    // 用户模块
    {
        routerUrls:'/api/user/login',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/userlist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/addlist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/register',
        menuUrl:'/',
        permit:null
    },
    {
        routerUrl:'/api/user/dellist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/updatelist',
        menuUrl:'/sys/user',
        permit:null
    },
    {
        routerUrl:'/api/user/isactiveuser',
        menuUrl:'/sys/user',
        permit:null
    },
    // 角色模块
    {
        routerUrl:'/api/role/addrole',
        menuUrl:'/sys/role',
        permit:null
    },
    {
        routerUrl:'/api/role/updaterole',
        menuUrl:'/sys/role',
        permit:'editRole'
    },
    {
        routerUrl:'/api/role/deleterole',
        menuUrl:'/sys/role',
        permit:null
    },
    {
        routerUrl:'/api/role/rolelist',
        menuUrl:'/sys/role',
        permit:null
    },
    // 菜单模块
    {
        routerUrl:'/api/menus/addmenulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/delMenuList',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/updatemenulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/menus/menulist',
        menuUrl:'/sys/menu',
        permit:null
    },
    {
        routerUrl:'/api/chatgpt/ask',
        menuUrl:'/chat',
        permit:null
    },
    {
        routerUrl:'/api/auth/emailcode',
        menuUrl:'/',
        permit:null
    }
]

module.exports=allRouterObj